<?php
/**
 * Blackbird InstallSchemaGenerator Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_InstallSchemaGenerator
 * @copyright       Copyright (c) 2017 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.store.bird.eu/license/
 */
?>
<?php
/**
 * @var \Blackbird\InstallSchemaGenerator\Block\InstallSchema\TableDeclaration\IndexDeclaration $block
 * @see \Blackbird\InstallSchemaGenerator\Block\InstallSchema\TableDeclaration\IndexDeclaration
 */
?>
<?php foreach ($block->getIndexes() as $indexName => $index): ?>
            ->addIndex(
                $installer->getIdxName(
                    '<?php echo $block->getTableName(); ?>',
                    [
<?php foreach ($index['columns'] as $column): ?>
                        '<?php echo $column; ?>',
<?php endforeach; ?>
                    ],
                    <?php echo $index['type'] ?: 'null', PHP_EOL; ?>
                ),
                [
<?php foreach ($index['columns'] as $column): ?>
                    '<?php echo $column; ?>',
<?php endforeach; ?>
                ],
                <?php echo $block->getIndexTypeArrayFormat($index['type']), PHP_EOL; ?>
            )
<?php endforeach; ?>
