<?php
/**
 * Blackbird InstallSchemaGenerator Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_InstallSchemaGenerator
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         MIT LICENSE
 */
?>
<?php
/**
 * @var \Blackbird\InstallSchemaGenerator\Block\InstallSchema\TableDeclaration\ColumnDeclaration $block
 * @see \Blackbird\InstallSchemaGenerator\Block\InstallSchema\TableDeclaration\ColumnDeclaration
 */
?>
            ->addColumn(
                '<?php echo $block->getColumnName(); ?>',
                Table::TYPE_<?php echo $block->getColumnType(); ?>,
                <?php echo $block->getColumnSize(); ?>,
                [
<?php foreach ($block->getOptions() as $key => $option): ?>
                    '<?php echo $key; ?>' => <?php echo in_array($option, ['true', 'false']) ? $option : '\'' . $option . '\'' ?>,
<?php endforeach; ?>
                ],
                '<?php echo $block->getColumnComment(); ?>'
            )
