<?php
/**
 * Blackbird Install Schema Generator Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category            Blackbird
 * @package		Blackbird_InstallSchemaGenerator
 * @copyright           Copyright (c) 2015 Blackbird (http://black.bird.eu)
 * @author		Blackbird Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php //$block->getFormAction(); ?>
<form action="<?= $block->getFormAction(); ?>" method="post" enctype="multipart/form-data" 
      class="form"  id="retrieve-form"
      data-hasrequired="<?= __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <?php echo $block->getBlockHtml('formkey')?>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= __('Select tables to retrieves their schema and make the install schema') ?></span></legend><br />
        <div class="field tables required">
            <label class="label" for="tables"><span><?= __('Select tables') ?></span></label>
            <div class="control">
                <select name="tables[]" id="tables" title="<?= __('Select tables') ?>" size="22" class="required-entry _required select multiselect admin__control-multiselect" multiple="multiple" required>
                    <?php foreach ($block->getTables() as $table) {
                        echo '<option value="' , $table['TABLE_NAME'] , '">' , $table['TABLE_NAME'] , '</option>';
                    } ?>
                </select>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= __('Get Install Schema') ?>" class="action submit primary">
                <span><?= __('Get Install Schema') ?></span>
            </button>
        </div>
    </div>
</form>